imA1 = imread("../../shapeContextsTestsData/A1.bmp");
imA2 = imread("../../shapeContextsTestsData/A2.bmp");
[ptsA1kY,ptsA1kX] = find(sum(imA1,3)>0);
[ptsA2kY,ptsA2kX] = find(sum(imA2,3)>0);
[ptsA1rY,ptsA1rX] = find(imA1(:,:,1)==255 & imA1(:,:,2)==0 & imA1(:,:,3)==0);
[ptsA1gY,ptsA1gX] = find(imA1(:,:,2)==255 & imA1(:,:,1)==0 & imA1(:,:,3)==0);
[ptsA2rY,ptsA2rX] = find(imA2(:,:,1)==255 & imA2(:,:,2)==0 & imA2(:,:,3)==0);
ptsA1 = [ptsA1kX, ptsA1kY];
ptsA2 = [ptsA2kX, ptsA2kY];
ptsA1r = [ptsA1rX, ptsA1rY];
ptsA1g = [ptsA1gX, ptsA1gY];
ptsA2r = [ptsA2rX, ptsA2rY];
fdA1r = shapeContext(ptsA1, ptsA1r);
fdA1g = shapeContext(ptsA1, ptsA1g);
fdA2r = shapeContext(ptsA2, ptsA2r);
fdsA1 = shapeContexts(ptsA1);
fdsA2 = shapeContexts(ptsA2);
visualizeShapeContext(fdA1r,5,12);
visualizeShapeContext(fdA2r,5,12);
visualizeShapeContext(fdA1g,5,12);
imshow(fdsA1);
imshow(fdsA2);
imshow([fdsA1; fdA1r]);
imshow([fdsA1; fdA1g]);
imshow([fdsA2; fdA2r]);
imshow(1-shapeContextCost(fdsA1,fdsA1));
imshow(1-shapeContextCost(fdsA2,fdsA2));
imshow(1-shapeContextCost(fdsA1,fdsA2));
plotImAndPts(imA1,ptsA1);
plotImAndPts(imA2,ptsA2);
plotImAndPts(imA1,ptsA1r);
plotImAndPts(imA1,ptsA1g);
plotImAndPts(imA2,ptsA2r);

imDisc = imread("../../shapeContextsTestsData/disc.bmp");
[ptsDisckY,ptsDisckX] = find(sum(imDisc,3)>0);
ptsDisc = [ptsDisckX, ptsDisckY];
fdDisc = shapeContext(ptsDisc, [size(imDisc,2)/2,size(imDisc,1)/2]);
fdsDisc = shapeContexts(ptsDisc);
visualizeShapeContext(fdDisc,5,12);
imshow(fdsDisc);
imshow(1-shapeContextCost(fdsDisc,fdsDisc));
